// examples/solid-start/src/routes/formatting.tsx
import type { Component } from 'solid-js'
import { useI18n, DateTime, NumberFormat } from '@fluenti/solid'
import { msg } from '@fluenti/core'

// Demonstrate msg`` for module-level message descriptors
const pageTitle = msg`Date & Number Formatting`

const Formatting: Component = () => {
  const { t: translate } = useI18n()

  return (
    <div>
      <h1>{translate(pageTitle)}</h1>

      <section style={{ 'margin-bottom': '24px' }}>
        <h2>{t`Today's date:`}</h2>
        <p>
          Default: <DateTime value={Date.now()} />
        </p>
        <p>
          Short: <DateTime value={Date.now()} style="short" />
        </p>
        <p>
          Long: <DateTime value={Date.now()} style="long" />
        </p>
        <p>
          Time: <DateTime value={Date.now()} style="time" />
        </p>
      </section>

      <section style={{ 'margin-bottom': '24px' }}>
        <h2>{t`A large number:`}</h2>
        <p>
          Default: <NumberFormat value={1234567.89} />
        </p>
      </section>

      <section style={{ 'margin-bottom': '24px' }}>
        <h2>{t`Percentage:`}</h2>
        <p>
          <NumberFormat value={0.75} style="percent" />
        </p>
      </section>

      <section>
        <h2>{t`Currency:`}</h2>
        <p>
          <NumberFormat value={99.99} style="currency" />
        </p>
      </section>
    </div>
  )
}

export default Formatting

// examples/vue/src/pages/Formatting.vue
<script setup lang="ts">
const now = Date.now()
const pastDate = new Date(Date.now() - 86400000 * 3)
</script>

<template>
  <h2 v-t>Formatting Demos</h2>

  <div class="section">
    <h2>Feature: &lt;DateTime&gt; Date Formatting</h2>

    <div class="demo-item">
      <div class="demo-label">&lt;DateTime :value="now" /&gt; — default</div>
      <div><DateTime :value="now" /></div>
    </div>

    <div class="demo-item">
      <div class="demo-label">&lt;DateTime :value="now" style="short" /&gt;</div>
      <div><DateTime :value="now" style="short" /></div>
    </div>

    <div class="demo-item">
      <div class="demo-label">&lt;DateTime :value="now" style="long" /&gt;</div>
      <div><DateTime :value="now" style="long" /></div>
    </div>

    <div class="demo-item">
      <div class="demo-label">&lt;DateTime :value="pastDate" style="relative" /&gt; — past date</div>
      <div><DateTime :value="pastDate" style="relative" /></div>
    </div>

    <div class="demo-item">
      <div class="demo-label">&lt;DateTime :value="now" style="datetime" /&gt;</div>
      <div><DateTime :value="now" style="datetime" /></div>
    </div>
  </div>

  <div class="section">
    <h2>Feature: &lt;NumberFormat&gt; Number Formatting</h2>

    <div class="demo-item">
      <div class="demo-label">&lt;NumberFormat :value="1234567.89" /&gt; — default</div>
      <div><NumberFormat :value="1234567.89" /></div>
    </div>

    <div class="demo-item">
      <div class="demo-label">&lt;NumberFormat :value="42.5" style="currency" /&gt;</div>
      <div><NumberFormat :value="42.5" style="currency" /></div>
    </div>

    <div class="demo-item">
      <div class="demo-label">&lt;NumberFormat :value="0.856" style="percent" /&gt;</div>
      <div><NumberFormat :value="0.856" style="percent" /></div>
    </div>

    <div class="demo-item">
      <div class="demo-label">&lt;NumberFormat :value="1234.5" style="decimal" /&gt;</div>
      <div><NumberFormat :value="1234.5" style="decimal" /></div>
    </div>
  </div>
</template>
