// examples/react-router/src/pages/Home.tsx
import { useI18n, msg } from '@fluenti/react'

const ROLES = {
  admin: msg`Administrator`,
  user: msg`Regular User`,
}

export function Home() {
  const { t, i18n, locale } = useI18n()
  const name = 'World'
  const count = 3
  return (
    <section data-testid="home-section">
      <h2 data-testid="welcome">{t`Welcome to Fluenti`}</h2>
      <p data-testid="subtitle">{t`A modern i18n library for React`}</p>
      <p data-testid="greeting">{t`Hello, ${name}!`}</p>
      <p data-testid="items">{t`You have ${count} items in your cart.`}</p>
      <p data-testid="current-locale">{t`Current locale: ${locale}`}</p>
      <p data-testid="date">{i18n.d(new Date(2025, 0, 15))}</p>
      <p data-testid="number">{i18n.n(1234.5)}</p>

      <div data-testid="msg-roles">
        <span data-testid="msg-admin">{i18n.t(ROLES.admin)}</span>
        {' / '}
        <span data-testid="msg-user">{i18n.t(ROLES.user)}</span>
      </div>
      <p data-testid="fallback-only">{t`This key only exists in English`}</p>

      <h3 data-testid="features-title">{t`Features`}</h3>
      <ul data-testid="features-list">
        <li>{t`Reactive locale switching`}</li>
        <li>{t`Rich text with React components`}</li>
        <li>{t`Built-in plural support`}</li>
        <li>{t`Type-safe message catalogs`}</li>
      </ul>
    </section>
  )
}

// examples/vue/src/pages/Home.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from '@fluenti/vue'
import { msg } from '@fluenti/core'

const { locale, t, format } = useI18n()

const serverTemplate = ref('{user} just {action}')

const ROLES = {
  admin: msg`Administrator`,
  user: msg`Regular User`,
}
</script>

<template>
  <h2 v-t>Welcome to Fluenti</h2>
  <p v-t>A modern i18n library for Vue 3</p>
  <p v-t>Fluenti provides reactive translations, rich text support, and plural handling out of the box.</p>

  <div class="section">
    <h2>t`` — Compile-time Translations</h2>
    <div class="demo-item">
      <div class="demo-label">t`Hello, ${'World'}!`</div>
      <div>{{ t`Hello, ${'World'}!` }}</div>
    </div>
    <div class="demo-item">
      <div class="demo-label">t`Current locale: ${locale}`</div>
      <div>{{ t`Current locale: ${locale}` }}</div>
    </div>
    <div class="demo-item">
      <div class="demo-label">t`You have ${5} items in your cart.`</div>
      <div>{{ t`You have ${5} items in your cart.` }}</div>
    </div>
  </div>

  <div class="section">
    <h2>format() — Direct ICU Formatting</h2>
    <p class="section-desc">Use <code>format()</code> for dynamic patterns not in the catalog — e.g. server-provided templates or user-generated content.</p>
    <div class="demo-item">
      <div class="demo-label">Server-provided template</div>
      <div>{{ format(serverTemplate, { user: 'Alice', action: 'logged in' }) }}</div>
    </div>
  </div>

  <div class="section">
    <h2 v-t>Features</h2>
    <ul>
      <li v-t>Reactive locale switching</li>
      <li v-t>Rich text with Vue components</li>
      <li v-t>Built-in plural support</li>
      <li v-t>Type-safe message catalogs</li>
    </ul>
  </div>

  <div class="section">
    <h2>msg`` — Lazy Messages from Constants</h2>
    <div class="demo-item">
      <div class="demo-label">msg`` — lazy messages from constants</div>
      <div>Admin: {{ t(ROLES.admin) }} / User: {{ t(ROLES.user) }}</div>
    </div>
  </div>

  <p data-testid="fallback-only">{{ t`This key only exists in English` }}</p>
</template>
