// examples/nextjs/src/app/[locale]/plurals/page.tsx
'use client'

import { useState } from 'react'
import { t, Plural, Select } from '@fluenti/react'

export default function PluralsPage() {
  const [count, setCount] = useState(0)
  const [gender, setGender] = useState('other')

  return (
    <div data-testid="plurals-section">
      <h2>{t`Plurals`}</h2>
      <div data-testid="plural-result">
        <Plural
          value={count}
          zero="No messages"
          one="# message"
          other="# messages"
        />
      </div>
      <div style={{ display: 'flex', gap: '8px', marginTop: '8px' }}>
        <button data-testid="btn-add" onClick={() => setCount(c => c + 1)}>
          {t`Add`}
        </button>
        <button data-testid="btn-remove" onClick={() => setCount(c => Math.max(0, c - 1))}>
          {t`Remove`}
        </button>
        <button data-testid="btn-reset" onClick={() => setCount(0)}>
          {t`Reset`}
        </button>
      </div>

      <h3>{t`Select Demo`}</h3>
      <div data-testid="select-result">
        <Select
          value={gender}
          male="He liked your post"
          female="She liked your post"
          other="They liked your post"
        />
      </div>
      <div style={{ display: 'flex', gap: '8px', marginTop: '8px' }}>
        <button data-testid="gender-male" onClick={() => setGender('male')}>{t`Male`}</button>
        <button data-testid="gender-female" onClick={() => setGender('female')}>{t`Female`}</button>
        <button data-testid="gender-other" onClick={() => setGender('other')}>{t`Other`}</button>
      </div>
    </div>
  )
}

// examples/nuxt/pages/plurals.vue
<script setup lang="ts">
import { ref } from 'vue'

const appleCount = ref(0)
const messageCount = ref(1)
const gender = ref('other')
</script>

<template>
  <div>
    <h2 v-t>Plural Demos</h2>

    <div class="section">
      <h2>&lt;Plural&gt; — Apples</h2>
      <div class="controls">
        <button @click="appleCount = Math.max(0, appleCount - 1)" v-t>Remove</button>
        <span class="counter-display">{{ appleCount }}</span>
        <button @click="appleCount++" v-t>Add</button>
        <button @click="appleCount = 0" v-t>Reset</button>
      </div>
      <div class="demo-item">
        <div class="demo-label">&lt;Plural :value="appleCount" zero/one/other&gt;</div>
        <Plural
          :value="appleCount"
          zero="No apples"
          one="1 apple"
          other="# apples"
        />
      </div>
    </div>

    <div class="section">
      <h2>&lt;Plural&gt; — Messages</h2>
      <div class="controls">
        <button @click="messageCount = Math.max(0, messageCount - 1)" v-t>Remove</button>
        <span class="counter-display">{{ messageCount }}</span>
        <button @click="messageCount++" v-t>Add</button>
        <button @click="messageCount = 0" v-t>Reset</button>
      </div>
      <div class="demo-item">
        <div class="demo-label">&lt;Plural :value="messageCount" zero/one/other&gt;</div>
        <Plural
          :value="messageCount"
          zero="No new messages"
          one="1 new message"
          other="# new messages"
        />
      </div>
    </div>

    <div class="section">
      <h2>Feature: &lt;Select&gt; Component</h2>
      <div class="controls">
        <button
          v-for="g in ['male', 'female', 'other']"
          :key="g"
          :data-testid="`gender-${g}`"
          :class="{ active: gender === g }"
          @click="gender = g"
        >
          {{ g }}
        </button>
      </div>
      <div class="demo-item">
        <div class="demo-label">&lt;Select :value="gender" ...&gt;</div>
        <div data-testid="select-result">
          <Select
            :value="gender"
            :options="{ male: 'He liked this', female: 'She liked this' }"
            other="They liked this"
          />
        </div>
      </div>
    </div>
  </div>
</template>
