// examples/solid-start/src/routes/plurals.tsx
import { createSignal } from 'solid-js'
import { t } from '@fluenti/solid'
import { Plural, Select } from '@fluenti/solid/components'

export default function PluralsPage() {
  const [count, setCount] = createSignal(0)
  const [gender, setGender] = createSignal('other')

  return (
    <div>
      <h1>{t`Plurals`}</h1>
      <p style={{ color: '#666', 'margin-bottom': '16px' }}>
        The Plural component selects the correct plural form based on Intl.PluralRules.
      </p>

      <div style={{
        background: 'white',
        padding: '24px',
        'border-radius': '8px',
        'box-shadow': '0 1px 3px rgba(0,0,0,0.1)',
        'text-align': 'center',
      }}>
        <div data-testid="plural-count" style={{
          'font-size': '48px',
          'font-weight': 'bold',
          'margin-bottom': '16px',
          color: '#4a90d9',
        }}>
          {count()}
        </div>

        <p data-testid="plural-result" style={{ 'font-size': '18px', 'margin-bottom': '24px' }}>
          <Plural
            value={count()}
            zero={t`Your cart is empty.`}
            one={t`You have # item in your cart.`}
            other={t`You have # items in your cart.`}
          />
        </p>

        <div style={{ display: 'flex', gap: '8px', 'justify-content': 'center' }}>
          <button
            data-testid="btn-dec"
            onClick={() => setCount((c) => Math.max(0, c - 1))}
            style={{
              padding: '8px 20px',
              'font-size': '18px',
              'border-radius': '4px',
              border: '1px solid #ddd',
              cursor: 'pointer',
            }}
          >
            -
          </button>
          <button
            data-testid="btn-inc"
            onClick={() => setCount((c) => c + 1)}
            style={{
              padding: '8px 20px',
              'font-size': '18px',
              'border-radius': '4px',
              border: '1px solid #ddd',
              cursor: 'pointer',
            }}
          >
            +
          </button>
          <button
            data-testid="btn-reset"
            onClick={() => setCount(0)}
            style={{
              padding: '8px 20px',
              'font-size': '14px',
              'border-radius': '4px',
              border: '1px solid #ddd',
              cursor: 'pointer',
            }}
          >
            {t`Reset`}
          </button>
        </div>
      </div>

      <div style={{
        background: 'white',
        padding: '24px',
        'border-radius': '8px',
        'box-shadow': '0 1px 3px rgba(0,0,0,0.1)',
        'margin-top': '24px',
      }}>
        <h2 style={{ 'margin-bottom': '16px' }}>{t`Select Demo`}</h2>
        <p data-testid="select-result" style={{ 'font-size': '18px', 'margin-bottom': '16px' }}>
          <Select
            value={gender()}
            options={{
              male: 'He liked your post',
              female: 'She liked your post',
            }}
            other="They liked your post"
          />
        </p>
        <div style={{ display: 'flex', gap: '8px', 'justify-content': 'center' }}>
          <button
            data-testid="gender-male"
            onClick={() => setGender('male')}
            style={{
              padding: '8px 20px',
              'border-radius': '4px',
              border: '1px solid #ddd',
              cursor: 'pointer',
              'font-weight': gender() === 'male' ? 'bold' : 'normal',
              background: gender() === 'male' ? '#4a90d9' : 'white',
              color: gender() === 'male' ? 'white' : '#333',
            }}
          >
            Male
          </button>
          <button
            data-testid="gender-female"
            onClick={() => setGender('female')}
            style={{
              padding: '8px 20px',
              'border-radius': '4px',
              border: '1px solid #ddd',
              cursor: 'pointer',
              'font-weight': gender() === 'female' ? 'bold' : 'normal',
              background: gender() === 'female' ? '#4a90d9' : 'white',
              color: gender() === 'female' ? 'white' : '#333',
            }}
          >
            Female
          </button>
          <button
            data-testid="gender-other"
            onClick={() => setGender('other')}
            style={{
              padding: '8px 20px',
              'border-radius': '4px',
              border: '1px solid #ddd',
              cursor: 'pointer',
              'font-weight': gender() === 'other' ? 'bold' : 'normal',
              background: gender() === 'other' ? '#4a90d9' : 'white',
              color: gender() === 'other' ? 'white' : '#333',
            }}
          >
            Other
          </button>
        </div>
      </div>
    </div>
  )
}

// examples/nextjs/src/app/[locale]/plurals/page.tsx
'use client'

import { useState } from 'react'
import { t } from '@fluenti/react'
import { Plural, Select } from '@fluenti/react/components'

export default function PluralsPage() {
  const [count, setCount] = useState(0)
  const [gender, setGender] = useState('other')

  return (
    <div data-testid="plurals-section">
      <h2>{t`Plurals`}</h2>
      <div data-testid="plural-result">
        <Plural
          value={count}
          zero="No messages"
          one="# message"
          other="# messages"
        />
      </div>
      <div style={{ display: 'flex', gap: '8px', marginTop: '8px' }}>
        <button data-testid="btn-add" onClick={() => setCount(c => c + 1)}>
          {t`Add`}
        </button>
        <button data-testid="btn-remove" onClick={() => setCount(c => Math.max(0, c - 1))}>
          {t`Remove`}
        </button>
        <button data-testid="btn-reset" onClick={() => setCount(0)}>
          {t`Reset`}
        </button>
      </div>

      <h3>{t`Select Demo`}</h3>
      <div data-testid="select-result">
        <Select
          value={gender}
          male="He liked your post"
          female="She liked your post"
          other="They liked your post"
        />
      </div>
      <div style={{ display: 'flex', gap: '8px', marginTop: '8px' }}>
        <button data-testid="gender-male" onClick={() => setGender('male')}>{t`Male`}</button>
        <button data-testid="gender-female" onClick={() => setGender('female')}>{t`Female`}</button>
        <button data-testid="gender-other" onClick={() => setGender('other')}>{t`Other`}</button>
      </div>
    </div>
  )
}
