// examples/svelte/src/App.svelte
<script lang="ts">
  import { setI18nContext, getI18n, Plural, Select, DateTime, Number as NumberFmt } from '@fluenti/svelte'
  import { msg } from '@fluenti/core'
  import en from './locales/compiled/en'
  import zhCN from './locales/compiled/zh-CN'
  import ja from './locales/compiled/ja'

  const i18n = setI18nContext({
    locale: 'en',
    fallbackLocale: 'en',
    messages: { en, 'zh-CN': zhCN, ja },
  })

  const localeLabels: Record<string, string> = {
    en: 'English',
    'zh-CN': '中文',
    ja: '日本語',
  }

  // Plural counters
  let appleCount = $state(0)
  let cartCount = $state(0)

  // Select gender
  let gender = $state('female')

  // Reactivity counter
  let reactivityCount = $state(0)

  // msg`` lazy messages
  const ROLES = {
    admin: msg`Administrator`,
    user: msg`Regular User`,
  }

  const now = Date.now()
</script>

<div class="app">
  <header>
    <div class="header-top">
      <h1>{i18n.t('Fluenti Svelte Playground')}</h1>
      <div class="lang-buttons">
        {#each i18n.getLocales() as loc}
          <button
            class:active={loc === i18n.locale}
            onclick={() => i18n.setLocale(loc)}
          >
            {localeLabels[loc] || loc}
          </button>
        {/each}
      </div>
    </div>
    <p class="tagline">{i18n.t('Write text. Fluenti translates it. Zero config.')}</p>
    {#if i18n.isLoading}
      <div class="loading-indicator">{i18n.t('Loading translations...')}</div>
    {/if}
  </header>

  <main>
    <!-- ═══════════════════════════════════════════ -->
    <!-- Welcome & Basic APIs                       -->
    <!-- ═══════════════════════════════════════════ -->
    <h2>{i18n.t('Welcome to Fluenti')}</h2>
    <p>{i18n.t('A type-safe i18n library for Svelte 5')}</p>

    <div class="section">
      <h2>t() — Catalog Translations</h2>
      <div class="demo-item">
        <div class="demo-label">t('Hello, {'{name}'}!', {'{ name: \'World\' }'})</div>
        <div>{i18n.t('Hello, {name}!', { name: 'World' })}</div>
      </div>
      <div class="demo-item">
        <div class="demo-label">t('Current locale: {'{locale}'}', {'{ locale }'})</div>
        <div>{i18n.t('Current locale: {locale}', { locale: i18n.locale })}</div>
      </div>
      <div class="demo-item">
        <div class="demo-label">t('You have {'{count}'} items in your cart.', {'{ count: 5 }'})</div>
        <div>{i18n.t('You have {count} items in your cart.', { count: 5 })}</div>
      </div>
    </div>

    <div class="section">
      <h2>format() — Direct ICU Formatting</h2>
      <div class="demo-item">
        <div class="demo-label">format('{'{count}'} items at {'{price}'} each', ...)</div>
        <div>{i18n.format('{count} items at {price} each', { count: 3, price: '$9.99' })}</div>
      </div>
    </div>

    <div class="section">
      <h2>d() — Date Formatting</h2>
      <div class="demo-item">
        <div class="demo-label">d(Date.now())</div>
        <div>{i18n.d(now)}</div>
      </div>
    </div>

    <div class="section">
      <h2>n() — Number Formatting</h2>
      <div class="demo-item">
        <div class="demo-label">n(1234567.89)</div>
        <div>{i18n.n(1234567.89)}</div>
      </div>
      <div class="demo-item">
        <div class="demo-label">n(0.42)</div>
        <div>{i18n.n(0.42)}</div>
      </div>
    </div>

    <div class="section">
      <h2>{i18n.t('Features')}</h2>
      <ul>
        <li>{i18n.t('Reactive locale switching')}</li>
        <li>{i18n.t('Rich text with Svelte components')}</li>
        <li>{i18n.t('Built-in plural support')}</li>
        <li>{i18n.t('Type-safe message catalogs')}</li>
      </ul>
    </div>

    <hr class="section-divider" />

    <!-- ═══════════════════════════════════════════ -->
    <!-- Script Features — msg``                    -->
    <!-- ═══════════════════════════════════════════ -->
    <div class="section">
      <h2>msg`` — Lazy Messages</h2>
      <div class="demo-item">
        <div class="demo-label">msg`` from constants</div>
        <div>Admin: {i18n.t(ROLES.admin)} / User: {i18n.t(ROLES.user)}</div>
      </div>
    </div>

    <hr class="section-divider" />

    <!-- ═══════════════════════════════════════════ -->
    <!-- Plural Demos                               -->
    <!-- ═══════════════════════════════════════════ -->
    <h2>Plural Component</h2>

    <div class="section">
      <h3>&lt;Plural&gt; — Apples</h3>
      <div class="controls">
        <button onclick={() => appleCount = Math.max(0, appleCount - 1)}>{i18n.t('Remove')}</button>
        <span class="counter-display">{appleCount}</span>
        <button onclick={() => appleCount++}>{i18n.t('Add')}</button>
        <button onclick={() => appleCount = 0}>{i18n.t('Reset')}</button>
      </div>
      <div class="demo-item">
        <Plural value={appleCount} zero="No apples" one="1 apple" other="# apples" />
      </div>
    </div>

    <div class="section">
      <h3>&lt;Plural&gt; — Cart Items</h3>
      <div class="controls">
        <button onclick={() => cartCount = Math.max(0, cartCount - 1)}>-</button>
        <span class="counter-display">{cartCount}</span>
        <button onclick={() => cartCount++}>+</button>
        <button onclick={() => cartCount = 0}>{i18n.t('Reset')}</button>
      </div>
      <div class="demo-item">
        <Plural
          value={cartCount}
          zero="Your cart is empty."
          one="You have # item in your cart."
          other="You have # items in your cart."
        />
      </div>
    </div>

    <hr class="section-divider" />

    <!-- ═══════════════════════════════════════════ -->
    <!-- Select Component                           -->
    <!-- ═══════════════════════════════════════════ -->
    <div class="section">
      <h2>Select Component</h2>
      <div class="controls">
        {#each ['male', 'female', 'other'] as g}
          <button
            class:active={gender === g}
            onclick={() => gender = g}
          >
            {g}
          </button>
        {/each}
      </div>
      <div class="demo-item">
        <Select
          value={gender}
          options={{ male: i18n.t('He liked this'), female: i18n.t('She liked this') }}
          other={i18n.t('They liked this')}
        />
      </div>
    </div>

    <hr class="section-divider" />

    <!-- ═══════════════════════════════════════════ -->
    <!-- DateTime and Number Components             -->
    <!-- ═══════════════════════════════════════════ -->
    <div class="section">
      <h2>&lt;DateTime&gt; Component</h2>
      <div class="demo-item">
        <div class="demo-label">&lt;DateTime value={'{now}'} /&gt;</div>
        <div><DateTime value={now} /></div>
      </div>
    </div>

    <div class="section">
      <h2>&lt;Number&gt; Component</h2>
      <div class="demo-item">
        <div class="demo-label">&lt;Number value={'{1234.56}'} /&gt;</div>
        <div><NumberFmt value={1234.56} /></div>
      </div>
    </div>

    <hr class="section-divider" />

    <!-- ═══════════════════════════════════════════ -->
    <!-- Reactivity Demo                            -->
    <!-- ═══════════════════════════════════════════ -->
    <div class="section">
      <h2>Reactivity Demo</h2>
      <div class="demo-item">
        <p class="counter-text">{i18n.t('Counter value: {count}', { count: reactivityCount })}</p>
        <div class="controls">
          <button onclick={() => reactivityCount--}>{i18n.t('Decrement')}</button>
          <button onclick={() => reactivityCount++}>{i18n.t('Increment')}</button>
          <button onclick={() => reactivityCount = 0}>{i18n.t('Reset')}</button>
        </div>
      </div>
    </div>

    <!-- ═══════════════════════════════════════════ -->
    <!-- Input Placeholder                          -->
    <!-- ═══════════════════════════════════════════ -->
    <div class="section">
      <h2>Attribute Translation</h2>
      <div class="demo-item">
        <input placeholder={i18n.t('Search products...')} class="demo-input" />
      </div>
    </div>
  </main>

  <footer>
    <p>{i18n.t('Built with Fluenti and Svelte 5')}</p>
  </footer>
</div>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

header {
  background: linear-gradient(135deg, #ff3e00 0%, #aa1100 100%);
  padding: 24px;
  border-radius: 12px;
  margin-bottom: 20px;
  color: #fff;
}

.header-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 12px;
}

header h1 {
  font-size: 1.5rem;
}

.tagline {
  margin-top: 8px;
  opacity: 0.9;
  font-size: 0.95rem;
}

.loading-indicator {
  margin-top: 8px;
  padding: 4px 12px;
  background: rgba(255,255,255,0.2);
  border-radius: 4px;
  font-size: 0.85rem;
  display: inline-block;
}

.lang-buttons {
  display: flex;
  gap: 6px;
}

button {
  padding: 6px 14px;
  border: 1px solid #ff3e00;
  background: #fff;
  color: #ff3e00;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.85rem;
  transition: all 0.15s;
}

button:hover {
  background: #ff3e00;
  color: #fff;
}

button.active {
  background: #ff3e00;
  color: #fff;
}

header .lang-buttons button {
  border-color: rgba(255,255,255,0.5);
  background: rgba(255,255,255,0.15);
  color: #fff;
}

header .lang-buttons button.active {
  background: #fff;
  color: #ff3e00;
}

main {
  background: #fff;
  padding: 24px;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  min-height: 300px;
}

.section-divider {
  border: none;
  border-top: 1px solid #e0e0e0;
  margin: 24px 0;
}

footer {
  text-align: center;
  padding: 20px;
  color: #999;
  font-size: 0.85rem;
}

.section {
  margin-bottom: 24px;
}

.section h2 {
  font-size: 1.2rem;
  color: #2c3e50;
  margin-bottom: 12px;
  border-bottom: 2px solid #ff3e00;
  padding-bottom: 4px;
}

.demo-item {
  padding: 8px 0;
  border-bottom: 1px solid #eee;
}

.demo-item:last-child {
  border-bottom: none;
}

.demo-label {
  font-size: 0.8rem;
  color: #999;
  font-family: monospace;
}

.controls {
  display: flex;
  gap: 8px;
  align-items: center;
  margin: 12px 0;
}

.counter-display {
  font-size: 1.5rem;
  font-weight: bold;
  color: #2c3e50;
  min-width: 40px;
  text-align: center;
}

.counter-text {
  font-size: 1.2rem;
  margin-bottom: 8px;
}

ul {
  padding-left: 20px;
}

li {
  padding: 4px 0;
}

.demo-input {
  padding: 6px 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  width: 220px;
}

a {
  color: #ff3e00;
  text-decoration: underline;
}
</style>

// examples/solid/src/App.tsx
import { createSignal, type Component, type JSX } from 'solid-js'
import { createFluentiSolid, useI18n, Trans, Plural, Select, DateTime, NumberFormat } from '@fluenti/solid'
import en from './locales/compiled/en.js'
import zhCN from './locales/compiled/zh-CN.js'
import ja from './locales/compiled/ja.js'

createFluentiSolid({
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en,
    'zh-CN': zhCN,
    ja,
  },
})

const Bold: Component<{ children?: JSX.Element }> = (props) => (
  <strong style={{ color: '#2c3e50' }}>{props.children}</strong>
)

const Italic: Component<{ children?: JSX.Element }> = (props) => (
  <em style={{ color: '#8e44ad' }}>{props.children}</em>
)

const Link: Component<{ children?: JSX.Element }> = (props) => (
  <a href="#" style={{ color: '#3498db', 'text-decoration': 'underline' }}>{props.children}</a>
)

const richComponents = { bold: Bold, italic: Italic, link: Link }

const LanguageSwitcher: Component = () => {
  const { locale, setLocale, isLoading, preloadLocale } = useI18n()

  const languages = [
    { code: 'en', label: 'English' },
    { code: 'zh-CN', label: '中文' },
    { code: 'ja', label: '日本語' },
  ] as const

  return (
    <div style={{ display: 'flex', gap: '8px', 'align-items': 'center' }}>
      {languages.map((lang) => (
        <button
          onClick={() => setLocale(lang.code)}
          onMouseEnter={() => preloadLocale(lang.code)}
          style={{
            'font-weight': locale() === lang.code ? 'bold' : 'normal',
            'background': locale() === lang.code ? '#4a90d9' : '#e0e0e0',
            'color': locale() === lang.code ? 'white' : '#333',
            'border': 'none',
            'padding': '6px 12px',
            'border-radius': '4px',
            'cursor': 'pointer',
          }}
        >
          {lang.label}
        </button>
      ))}
      {isLoading() && <span style={{ color: '#999', 'font-size': '0.85rem' }}>Loading...</span>}
    </div>
  )
}

export const App: Component = () => {
  const { t, d, n, format, locale } = useI18n()
  const [name, setName] = createSignal('Developer')
  const [compileCount, setCompileCount] = createSignal(3)
  const [price, setPrice] = createSignal(29.99)
  const [pluralCount, setPluralCount] = createSignal(0)
  const [reactivityCount, setReactivityCount] = createSignal(0)
  const [gender, setGender] = createSignal('female')
  const formattedPrice = () => '$' + price()
  const developer = 'Developer'

  const now = Date.now()
  const pastDate = new Date(Date.now() - 86400000 * 3)

  console.log('[Reactivity] Component body executed — this should appear only once!')

  const cardStyle = {
    background: 'white',
    padding: '16px',
    'border-radius': '8px',
    'box-shadow': '0 1px 3px rgba(0,0,0,0.1)',
  }

  const demoItemStyle = {
    'margin-bottom': '12px',
  }

  const demoLabelStyle = {
    'font-size': '0.85rem',
    color: '#999',
    'font-family': 'monospace',
    'margin-bottom': '4px',
  }

  return (
    <div style={{
      'max-width': '800px',
      'margin': '0 auto',
      'padding': '24px',
    }}>
      <header style={{
        'display': 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        'margin-bottom': '24px',
        'padding-bottom': '16px',
        'border-bottom': '1px solid #ddd',
      }}>
        <LanguageSwitcher />
      </header>
      <main style={{ 'display': 'flex', 'flex-direction': 'column', 'gap': '32px' }}>

        {/* ── Home ── */}
        <div>
          <h1>{t`Welcome to Fluenti`}</h1>
          <p style={{ color: '#666', 'margin-bottom': '16px' }}>{t`A type-safe i18n library for Solid`}</p>

          <section style={{ 'margin-bottom': '24px' }}>
            <h2>{t`Hello, ${developer}!`}</h2>
            <p>{t`This playground demonstrates the features of @fluenti/solid.`}</p>
            <p style={{ 'margin-top': '8px', 'font-style': 'italic' }}>
              {t`Current locale: ${locale()}`}
            </p>
          </section>

          <section style={cardStyle}>
            <h3 style={{ 'margin-bottom': '12px' }}>{t`Username`}</h3>
            <div style={{ display: 'flex', 'flex-direction': 'column', gap: '8px' }}>
              <label>
                {t`Username`}
                <input type="text" placeholder={t`Username`} style={{ 'margin-left': '8px' }} />
              </label>
              <label>
                {t`Email`}
                <input type="email" placeholder={t`Email`} style={{ 'margin-left': '8px' }} />
              </label>
              <label>
                {t`Password`}
                <input type="password" placeholder={t`Password`} style={{ 'margin-left': '8px' }} />
              </label>
              <small style={{ color: '#999' }}>{t`This field is required`}</small>
              <div style={{ display: 'flex', gap: '8px', 'margin-top': '8px' }}>
                <button>{t`Submit`}</button>
                <button>{t`Cancel`}</button>
              </div>
            </div>
          </section>
        </div>

        <hr style={{ border: 'none', 'border-top': '1px solid #ddd' }} />

        {/* ── Compile-Time Transforms ── */}
        <div>
          <h1>{t`Compile-Time Transforms`}</h1>
          <p style={{ color: '#666', 'margin-bottom': '16px' }}>
            {t`These demos showcase compile-time features: function calls and tagged templates — all transformed at build time by the Vite plugin.`}
          </p>

          <section style={{ ...cardStyle, 'margin-bottom': '16px' }}>
            <h2 style={{ 'margin-bottom': '12px', color: '#2c3e50' }}>
              Tagged Template — Source Text as Key
            </h2>
            <p style={{ color: '#888', 'font-size': '0.85rem', 'margin-bottom': '12px' }}>
              <code>{'t`source text`'}</code> tagged templates use the source text as the key. The CLI extracts it,
              translators translate it, and the compiled output maps it to the right locale.
            </p>

            <div style={{ 'border-bottom': '1px solid #eee', 'padding': '8px 0' }}>
              <div style={{ 'font-family': 'monospace', 'font-size': '0.8rem', color: '#999' }}>
                {'t`Hello, ${name()}!`'}
              </div>
              <div>{t`Hello, ${name()}!`}</div>
            </div>

            <div style={{ 'border-bottom': '1px solid #eee', 'padding': '8px 0' }}>
              <div style={{ 'font-family': 'monospace', 'font-size': '0.8rem', color: '#999' }}>
                {'t`You have ${compileCount()} items.`'}
              </div>
              <div>{t`You have ${compileCount()} items.`}</div>
            </div>

            <div style={{ 'padding': '8px 0' }}>
              <div style={{ 'font-family': 'monospace', 'font-size': '0.8rem', color: '#999' }}>
                {'t`Current locale: ${locale()}`'}
              </div>
              <div>{t`Current locale: ${locale()}`}</div>
            </div>
          </section>

          <section style={cardStyle}>
            <h2 style={{ 'margin-bottom': '12px', color: '#2c3e50' }}>
              Interactive — Reactive Signals
            </h2>

            <div style={{ 'border-bottom': '1px solid #eee', 'padding': '8px 0' }}>
              <label>
                Name:
                <input
                  value={name()}
                  onInput={(e) => setName(e.currentTarget.value)}
                  style={{ 'margin-left': '8px', padding: '4px 8px', border: '1px solid #ddd', 'border-radius': '4px' }}
                />
              </label>
              <div style={{ 'margin-top': '4px' }}>{t`Hello, ${name()}!`}</div>
            </div>

            <div style={{ 'border-bottom': '1px solid #eee', 'padding': '8px 0' }}>
              <div style={{ display: 'flex', gap: '8px', 'align-items': 'center' }}>
                <button
                  onClick={() => setCompileCount((c) => Math.max(0, c - 1))}
                  style={{ padding: '4px 12px', border: '1px solid #ddd', 'border-radius': '4px', cursor: 'pointer' }}
                >-</button>
                <span style={{ 'font-size': '1.5rem', 'font-weight': 'bold', 'min-width': '40px', 'text-align': 'center' }}>
                  {compileCount()}
                </span>
                <button
                  onClick={() => setCompileCount((c) => c + 1)}
                  style={{ padding: '4px 12px', border: '1px solid #ddd', 'border-radius': '4px', cursor: 'pointer' }}
                >+</button>
              </div>
              <div style={{ 'margin-top': '4px' }}>{t`You have ${compileCount()} items in your cart.`}</div>
            </div>

            <div style={{ 'padding': '8px 0' }}>
              <label>
                Price:
                <input
                  type="number"
                  step="0.01"
                  value={price()}
                  onInput={(e) => setPrice(parseFloat(e.currentTarget.value) || 0)}
                  style={{ 'margin-left': '8px', padding: '4px 8px', border: '1px solid #ddd', 'border-radius': '4px', width: '100px' }}
                />
              </label>
              <div style={{ 'margin-top': '4px' }}>{t`Total: ${formattedPrice()}`}</div>
            </div>
          </section>
        </div>

        <hr style={{ border: 'none', 'border-top': '1px solid #ddd' }} />

        {/* ── Rich Text ── */}
        <div>
          <h1>{t`Rich Text`}</h1>
          <p style={{ color: '#666', 'margin-bottom': '16px' }}>
            The Trans component renders rich text with embedded components.
          </p>

          <div style={{ display: 'flex', 'flex-direction': 'column', gap: '16px' }}>
            <div style={cardStyle}>
              <h3 style={{ 'margin-bottom': '8px' }}>Welcome Message</h3>
              <p>
                <Trans
                  message={t`Welcome to <bold>Fluenti</bold> for <italic>SolidJS</italic>!`}
                  components={richComponents}
                />
              </p>
            </div>

            <div style={cardStyle}>
              <h3 style={{ 'margin-bottom': '8px' }}>Feature List</h3>
              <p>
                <Trans
                  message={t`Supports <bold>bold</bold>, <italic>italic</italic>, and <link>links</link>.`}
                  components={richComponents}
                />
              </p>
            </div>

            <div style={cardStyle}>
              <h3 style={{ 'margin-bottom': '8px' }}>Nested Components</h3>
              <p>
                <Trans
                  message={t`You can even <bold>nest <italic>components</italic> inside</bold> each other.`}
                  components={richComponents}
                />
              </p>
            </div>
          </div>
        </div>

        <hr style={{ border: 'none', 'border-top': '1px solid #ddd' }} />

        {/* ── Plurals ── */}
        <div>
          <h1>{t`Plurals`}</h1>
          <p style={{ color: '#666', 'margin-bottom': '16px' }}>
            The Plural component selects the correct plural form based on Intl.PluralRules.
          </p>

          <div style={{ ...cardStyle, padding: '24px', 'text-align': 'center' }}>
            <div style={{
              'font-size': '48px',
              'font-weight': 'bold',
              'margin-bottom': '16px',
              color: '#4a90d9',
            }}>
              {pluralCount()}
            </div>

            <p style={{ 'font-size': '18px', 'margin-bottom': '24px' }}>
              <Plural
                value={pluralCount()}
                zero={t`Your cart is empty.`}
                one={t`You have # item in your cart.`}
                other={t`You have # items in your cart.`}
              />
            </p>

            <div style={{ display: 'flex', gap: '8px', 'justify-content': 'center' }}>
              <button
                onClick={() => setPluralCount((c) => Math.max(0, c - 1))}
                style={{
                  padding: '8px 20px',
                  'font-size': '18px',
                  'border-radius': '4px',
                  border: '1px solid #ddd',
                  cursor: 'pointer',
                }}
              >
                -
              </button>
              <button
                onClick={() => setPluralCount((c) => c + 1)}
                style={{
                  padding: '8px 20px',
                  'font-size': '18px',
                  'border-radius': '4px',
                  border: '1px solid #ddd',
                  cursor: 'pointer',
                }}
              >
                +
              </button>
              <button
                onClick={() => setPluralCount(0)}
                style={{
                  padding: '8px 20px',
                  'font-size': '14px',
                  'border-radius': '4px',
                  border: '1px solid #ddd',
                  cursor: 'pointer',
                }}
              >
                {t`Reset`}
              </button>
            </div>
          </div>
        </div>

        <hr style={{ border: 'none', 'border-top': '1px solid #ddd' }} />

        {/* ── Reactivity Demo ── */}
        <div>
          <h1>{t`Reactivity Demo`}</h1>
          <p style={{ color: '#666', 'margin-bottom': '16px' }}>
            {t`In SolidJS, the component body runs only once. Text nodes update reactively.`}
          </p>

          <div style={{ ...cardStyle, padding: '24px', 'margin-bottom': '16px' }}>
            <h3 style={{ 'margin-bottom': '12px' }}>Signal Counter</h3>
            <p style={{ 'font-size': '24px', 'margin-bottom': '16px' }}>
              {t`Counter value: ${reactivityCount()}`}
            </p>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button onClick={() => setReactivityCount((c) => c - 1)}>
                {t`Decrement`}
              </button>
              <button onClick={() => setReactivityCount((c) => c + 1)}>
                {t`Increment`}
              </button>
              <button onClick={() => setReactivityCount(0)}>
                {t`Reset`}
              </button>
            </div>
          </div>

          <div style={{
            background: '#fffbea',
            padding: '16px',
            'border-radius': '8px',
            border: '1px solid #f0e68c',
          }}>
            <h3 style={{ 'margin-bottom': '8px' }}>How it works</h3>
            <ul style={{ 'padding-left': '20px' }}>
              <li>The component function runs <strong>once</strong></li>
              <li>
                <code>t()</code> reads <code>locale()</code> internally, making it reactive
              </li>
              <li>Changing locale updates all translated text without re-running the component</li>
              <li>Open the console to see the proof — the log message appears only once</li>
              <li>Current locale: <strong>{locale()}</strong></li>
            </ul>
          </div>
        </div>

        <hr style={{ border: 'none', 'border-top': '1px solid #ddd' }} />

        {/* ── Formatting Showcase ── */}
        <div>
          <h1>{t`Formatting Showcase`}</h1>
          <p style={{ color: '#666', 'margin-bottom': '16px' }}>
            Date formatting, number formatting, direct ICU interpolation, and select components.
          </p>

          <section style={{ 'margin-bottom': '24px' }}>
            <h2 style={{ 'margin-bottom': '12px' }}>Feature: d() Date Formatting</h2>
            <div style={cardStyle}>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>d(date) — default</div>
                <div>{d(now)}</div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>d(date, 'short')</div>
                <div>{d(now, 'short')}</div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>d(date, 'long')</div>
                <div>{d(now, 'long')}</div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>d(date, 'relative') — past date</div>
                <div>{d(pastDate, 'relative')}</div>
              </div>
            </div>
          </section>

          <section style={{ 'margin-bottom': '24px' }}>
            <h2 style={{ 'margin-bottom': '12px' }}>Feature: n() Number Formatting</h2>
            <div style={cardStyle}>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>n(1234567.89) — default</div>
                <div>{n(1234567.89)}</div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>n(42.5, 'currency')</div>
                <div>{n(42.5, 'currency')}</div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>n(0.856, 'percent')</div>
                <div>{n(0.856, 'percent')}</div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>n(1234.5, 'decimal')</div>
                <div>{n(1234.5, 'decimal')}</div>
              </div>
            </div>
          </section>

          <section style={{ 'margin-bottom': '24px' }}>
            <h2 style={{ 'margin-bottom': '12px' }}>{'Feature: <DateTime> & <NumberFormat> Components'}</h2>
            <div style={cardStyle}>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>{'<DateTime value={Date.now()} />'}</div>
                <div><DateTime value={Date.now()} /></div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>{'<DateTime value={Date.now()} style="long" />'}</div>
                <div><DateTime value={Date.now()} style="long" /></div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>{'<NumberFormat value={1234567.89} />'}</div>
                <div><NumberFormat value={1234567.89} /></div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>{'<NumberFormat value={42.5} style="currency" />'}</div>
                <div><NumberFormat value={42.5} style="currency" /></div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>{'<NumberFormat value={0.856} style="percent" />'}</div>
                <div><NumberFormat value={0.856} style="percent" /></div>
              </div>
            </div>
          </section>

          <section style={{ 'margin-bottom': '24px' }}>
            <h2 style={{ 'margin-bottom': '12px' }}>Feature: format() Direct ICU Interpolation</h2>
            <div style={cardStyle}>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>format(serverTemplate, values)</div>
                <div>
                  {format('Hello {name}, you have {count} notifications', {
                    name: 'Developer',
                    count: 5,
                  })}
                </div>
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>format(template) — no values</div>
                <div>{format('Welcome to the app!')}</div>
              </div>
            </div>
          </section>

          <section style={{ 'margin-bottom': '24px' }}>
            <h2 style={{ 'margin-bottom': '12px' }}>{'Feature: <Select> Component'}</h2>
            <div style={cardStyle}>
              <div style={{ display: 'flex', gap: '8px', 'margin-bottom': '16px' }}>
                {(['male', 'female', 'other'] as const).map((g) => (
                  <button
                    onClick={() => setGender(g)}
                    style={{
                      'font-weight': gender() === g ? 'bold' : 'normal',
                      background: gender() === g ? '#4a90d9' : '#e0e0e0',
                      color: gender() === g ? 'white' : '#333',
                      border: 'none',
                      padding: '6px 12px',
                      'border-radius': '4px',
                      cursor: 'pointer',
                    }}
                  >
                    {g}
                  </button>
                ))}
              </div>
              <div style={demoItemStyle}>
                <div style={demoLabelStyle}>{'<Select value={gender} options={...} other="..." />'}</div>
                <div>
                  <Select
                    value={gender()}
                    options={{
                      male: t`He liked this`,
                      female: t`She liked this`,
                    }}
                    other={t`They liked this`}
                  />
                </div>
              </div>
            </div>
          </section>
        </div>

      </main>
    </div>
  )
}
