// examples/react/src/main.tsx
import { createRoot } from 'react-dom/client'
import { I18nProvider } from '@fluenti/react'
import { useState } from 'react'
import en from './locales/compiled/en'
import zhCN from './locales/compiled/zh-CN'
import ja from './locales/compiled/ja'
import { App } from './App'

const messages = { en, 'zh-CN': zhCN, ja }

function Root() {
  const [locale, setLocale] = useState('en')
  return (
    <I18nProvider
      locale={locale}
      fallbackLocale="en"
      messages={messages}
    >
      <App onLocaleChange={setLocale} />
    </I18nProvider>
  )
}

createRoot(document.getElementById('root')!).render(<Root />)

// examples/solid/src/index.tsx
import { render } from 'solid-js/web'
import { I18nProvider } from '@fluenti/solid'
import { App } from './App'
import en from './locales/compiled/en.js'
import zhCN from './locales/compiled/zh-CN.js'
import ja from './locales/compiled/ja.js'

const root = document.getElementById('root')

if (!root) {
  throw new Error('Root element not found')
}

render(
  () => (
    <I18nProvider
      locale="en"
      fallbackLocale="en"
      messages={{ en, 'zh-CN': zhCN, ja }}
    >
      <App />
    </I18nProvider>
  ),
  root,
)
