// packages/react/src/types.ts
import type { ReactNode } from 'react'
import type {
  Locale,
  LocalizedString,
  Messages,
  AllMessages,
  MessageDescriptor,
  CompileTimeMessageDescriptor,
  CompileTimeT,
  DateFormatOptions,
  NumberFormatOptions,
  FluentInstanceExtended,
} from '@fluenti/core'

export interface FluentiContext {
  /** The underlying Fluent instance (escape hatch for advanced use) */
  i18n: FluentInstanceExtended
  /** Translate a message by id with optional interpolation values */
  t: {
    (id: string | MessageDescriptor, values?: Record<string, unknown>): LocalizedString
    (strings: TemplateStringsArray, ...exprs: unknown[]): LocalizedString
  }
  /** Format a date value for the current locale */
  d: (value: Date | number, style?: string) => LocalizedString
  /** Format a number value for the current locale */
  n: (value: number, style?: string) => LocalizedString
  /** Format an ICU message string directly (no catalog lookup) */
  format: (message: string, values?: Record<string, unknown>) => LocalizedString
  /** Merge additional messages into a locale catalog at runtime */
  loadMessages: (locale: string, messages: Messages) => void
  /** Return all locale codes that have loaded messages */
  getLocales: () => string[]
  /** Current locale */
  locale: string
  /** Change the active locale (async when lazy loading) */
  setLocale: (locale: string) => Promise<void>
  /** Whether a locale is currently being loaded */
  isLoading: boolean
  /** Set of locales whose messages have been loaded */
  loadedLocales: string[]
  /** Preload a locale in the background without switching to it */
  preloadLocale: (locale: string) => Promise<void>
}

export interface I18nProviderProps {
  /** Active locale code */
  locale: string
  /** Fallback locale when translation is missing */
  fallbackLocale?: string
  /** Static message catalogs */
  messages?: AllMessages
  /** Async loader for lazy loading */
  loadMessages?: (locale: string) => Promise<Messages | { default: Messages }>
  /** Custom fallback chains per locale */
  fallbackChain?: Record<string, string[]>
  /** Date format styles */
  dateFormats?: DateFormatOptions
  /** Number format styles */
  numberFormats?: NumberFormatOptions
  /** Missing message handler */
  missing?: (locale: Locale, id: string) => string | undefined
  /** App content */
  children: ReactNode
}

/** @deprecated Use `FluentiContext` instead */
export type I18nContextValue = FluentiContext

export type {
  Locale,
  LocalizedString,
  Messages,
  AllMessages,
  MessageDescriptor,
  CompileTimeMessageDescriptor,
  CompileTimeT,
  DateFormatOptions,
  NumberFormatOptions,
  FluentInstanceExtended,
}

// packages/solid/src/types.ts
import type { Accessor } from 'solid-js'
import type {
  FluentiCoreConfig,
  Locale,
  LocalizedString,
  Messages,
  CompiledMessage,
  MessageDescriptor,
  DateFormatOptions,
  NumberFormatOptions,
} from '@fluenti/core'

/** Chunk loader for lazy locale loading */
export type ChunkLoader = (
  locale: string,
) => Promise<Record<string, CompiledMessage> | { default: Record<string, CompiledMessage> }>

/** Extended config with lazy locale loading support */
export interface FluentiConfig extends FluentiCoreConfig {
  /** Async chunk loader for lazy locale loading */
  chunkLoader?: ChunkLoader
  /** Enable lazy locale loading through chunkLoader */
  lazyLocaleLoading?: boolean
  /** Named date format styles */
  dateFormats?: DateFormatOptions
  /** Named number format styles */
  numberFormats?: NumberFormatOptions
}

/** Reactive i18n context holding locale signal and translation utilities */
export interface FluentiContext {
  /** Reactive accessor for the current locale */
  locale(): Locale
  /** Set the active locale (async when lazy locale loading is enabled) */
  setLocale(locale: Locale): Promise<void>
  /** Translate a message by id with optional interpolation values */
  t(id: string | MessageDescriptor, values?: Record<string, unknown>): LocalizedString
  /** Tagged template form: t`Hello ${name}` */
  t(strings: TemplateStringsArray, ...exprs: unknown[]): LocalizedString
  /** Merge additional messages into a locale catalog at runtime */
  loadMessages(locale: Locale, messages: Messages): void
  /** Return all locale codes that have loaded messages */
  getLocales(): Locale[]
  /** Format a date value for the current locale */
  d(value: Date | number, style?: string): LocalizedString
  /** Format a number value for the current locale */
  n(value: number, style?: string): LocalizedString
  /** Format an ICU message string directly (no catalog lookup) */
  format(message: string, values?: Record<string, unknown>): LocalizedString
  /** Whether a locale chunk is currently being loaded */
  isLoading: Accessor<boolean>
  /** Set of locales whose messages have been loaded */
  loadedLocales: Accessor<Set<string>>
  /** Preload a locale in the background without switching to it */
  preloadLocale(locale: string): void
}
