// packages/react/src/hooks/useI18n.ts
import { useContext } from 'react'
import { I18nContext } from '../context'
import type { FluentiContext } from '../types'

/**
 * Primary hook for accessing i18n functions.
 *
 * Returns locale, setLocale, isLoading, loadedLocales, preloadLocale,
 * and the underlying i18n instance with t(), d(), n() methods.
 *
 * @throws If used outside of `<I18nProvider>`
 */
export function useI18n(): FluentiContext {
  const ctx = useContext(I18nContext)
  if (!ctx) {
    throw new Error(
      '[fluenti] useI18n() must be used within an <I18nProvider>. ' +
        'Wrap your app with <I18nProvider> to provide i18n context.',
    )
  }
  return ctx
}

/**
 * Shorthand hook that returns only the current locale string.
 *
 * @example
 * ```tsx
 * const locale = useLocale() // 'en'
 * ```
 */
export function useLocale(): string {
  return useI18n().locale
}

// packages/solid/src/use-i18n.ts
import { useContext } from 'solid-js'
import { I18nCtx } from './provider'
import type { FluentiContext } from './context'

/**
 * Access the i18n context from the nearest `<I18nProvider>`.
 *
 * Throws if no provider is found in the component tree.
 */
export function useI18n(): FluentiContext {
  const ctx = useContext(I18nCtx)
  if (ctx) {
    return ctx
  }

  throw new Error(
    'useI18n() must be used inside an <I18nProvider>.',
  )
}

/** Shorthand hook that returns only the current locale accessor. */
export function useLocale(): () => string {
  return useI18n().locale
}
