// examples/nuxt/pages/rich-text.vue
<script setup lang="ts">
</script>

<template>
  <div>
    <h2 v-t>Rich Text Demos</h2>

    <div class="section">
      <h2>&lt;Trans&gt; — Rich Text with Components</h2>

      <div class="demo-item">
        <div class="demo-label">Link example (external &lt;a&gt;)</div>
        <Trans>Visit our <a href="https://github.com" target="_blank">documentation</a> to learn more.</Trans>
      </div>

      <div class="demo-item">
        <div class="demo-label">Bold example (&lt;strong&gt;)</div>
        <Trans>This is <strong>important</strong> information.</Trans>
      </div>

      <div class="demo-item">
        <div class="demo-label">Combined: link + bold</div>
        <Trans>Please <a href="#" @click.prevent>sign in</a> or <strong>register</strong> to continue.</Trans>
      </div>
    </div>
  </div>
</template>

<style scoped>
a {
  color: #00dc82;
  text-decoration: underline;
}

strong {
  color: #e74c3c;
}
</style>

// examples/nextjs/src/app/[locale]/richtext/page.tsx
'use client'

import { t, Trans, msg, useI18n } from '@fluenti/react'

const PAGE_LABELS = {
  title: msg`Rich Text Demos`,
  subtitle: msg`Components for complex translations`,
}

export default function RichTextPage() {
  const { i18n } = useI18n()

  return (
    <div data-testid="richtext-section">
      <h2 data-testid="richtext-title">{i18n.t(PAGE_LABELS.title)}</h2>
      <p data-testid="richtext-subtitle">{i18n.t(PAGE_LABELS.subtitle)}</p>

      <p data-testid="trans-basic">
        <Trans>Read the <a href="/docs">documentation</a> for more info.</Trans>
      </p>
      <p data-testid="trans-bold">
        <Trans>This is <strong>important</strong> information.</Trans>
      </p>
      <p data-testid="trans-multi">
        <Trans>Please <a href="/login">sign in</a> or <strong>register</strong> to continue.</Trans>
      </p>
    </div>
  )
}
